/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';
import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';

const components = [
  Button,
  Row,
  Col
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Button,
  Row,
  Col
};
