/* Automatically generated by './build/bin/build-entry.js' */

import Row from '../packages/row/index.js';
import Col from '../packages/col/index.js';
import Button from '../packages/button/index.js';
import Input from '../packages/input/index.js';
import Form from '../packages/form/index.js';

const components = [
  Row,
  Col,
  Button,
  Input,
  Form
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  install,
  Row,
  Col,
  Button,
  Input,
  Form
};
